name = "Erosion"
uuid = "1d686ed2-f4cc-40f7-813c-2f806c81b237"
authors = ["Cédric BELMANT"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
